#!/bin/bash
##
#Allmon add/delete user access
#
#by n8thn
#V1.0
#release date 20190311
#
if [ `whoami` != root ]; then
        whiptail --msgbox "This script must be run as root or with sudo" 20 60 2
        exit 1
fi

logfile=/tmp/allmon-ssword.log
WEBROOT=/var/www/html
#PASSWORDFILE=/var/www/html/allmon/.htpasswd
PASSWORDFILE=$WEBROOT/allmon2/.htpasswd

echo "" > $logfile

calc_wt_size() {
echo "doing calc_wt_size" >> $logfile
WT_HEIGHT=22
WT_WIDTH=$(tput cols)
if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
	WT_WIDTH=80
fi
if [ "$WT_WIDTH" -gt 178 ]; then
	WT_WIDTH=120
	fi
	WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

do_info() {
echo "do_info" >> $logfile
whiptail --msgbox "Add or delete a users access to control of Allmon" 20 60 2
}

get_allmon_users() {
echo "get_allmon_users" >> $logfile
if [ -f $PASSWORDFILE ]; then
	USERS=$(cat $PASSWORDFILE | awk -F":" '{print $1}')
else
	USERS=NONE
fi
}

add_allmon_user() {
echo "add_allmon_user" >> $logfile
NEWUSERNAME_PASSWD1="A"
NEWUSERNAME_PASSWD2="B"
get_allmon_users

if (whiptail --title "Add user login?" --yesno "Current user login names are:\n$USERS" 20 60) then
	NEWUSERNAME=$(whiptail --inputbox "Enter new login name you would like to add" 8 78 --title "Login name add" 3>&1 1>&2 2>&3)
	# check if passwd1 = passwd2 if not re-enter
        while [ "$NEWUSERNAME_PASSWD1" != "$NEWUSERNAME_PASSWD2" ]; do
        whiptail --msgbox "Passwords must match" 8 78 3>&1 1>&2 2>&3
        NEWUSERNAME_PASSWD1=$(whiptail --passwordbox "please enter a password for $NEWUSERNAME" 8 78 --title "password dialog" 3>&1 1>&2 2>&3)
        NEWUSERNAME_PASSWD2=$(whiptail --passwordbox "please verify password for $NEWUSERNAME" 8 78 --title "password dialog" 3>&1 1>&2 2>&3)
        done

        if [ -f $PASSWORDFILE ]; then
	        htpasswd -bd $PASSWORDFILE $NEWUSERNAME $NEWUSERNAME_PASSWD1 > /dev/null 2>&1
        else
	        htpasswd -bcd $PASSWORDFILE $NEWUSERNAME $NEWUSERNAME_PASSWD1 > /dev/null 2>&1
        fi
        whiptail --msgbox "User $NEWUSERNAME has been added to Allmon control access list" 20 60 2
fi

}

del_allmon_user() {
echo "del_allmon_user" >> $logfile
get_allmon_users
if (whiptail --title "Delete user login?" --yesno "Current user login names are:\n$USERS" 20 60) then
	DELUSERNAME=$(whiptail --inputbox "$USERS \nEnter login name you would like to delete" 8 78 --title "Login name delete" 3>&1 1>&2 2>&3)
	htpasswd -D $PASSWORDFILE $DELUSERNAME > /dev/null 2>&1
	whiptail --msgbox "User $DELUSERNAME has been removed" 20 60 2
fi
}

allmon_user_menu() {
echo "allmon_user_menu" >> $logfile
RET=0
while true; do
calc_wt_size
FUN=$(whiptail --menu "Allmon user access" --title "Allmon user access" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --ok-button Select --cancel-button Exit \
"A " "Information" \
"B " "Add user access to Allmon" \
"C " "Delete user access to Allmon" \
3>&1 1>&2 2>&3)
RET=$?
if [ $RET -eq 1 ]; then
	return
elif [ $RET -eq 0 ]; then
	case "$FUN" in
	A\ *) do_info ;;
	B\ *) add_allmon_user ;;
	C\ *) del_allmon_user ;;
	*) whiptail --msgbox "Programmer error: unrecognized option" 20 60 1 ;;
	esac || whiptail --msgbox "Invalid option, please try again" 20 60 1
else
	exit 1
fi
done

}

clear
allmon_user_menu
