#!/bin/bash
#-----

### add following to rpt.conf in [node_number] stanza ### just look for the line starting with connpgm=
#
#connpgm=/usr/local/bin/msg_on_connect
#

# uncomment the following line if you use Supermon and want to use smlogger
#/usr/local/sbin/supermon/smlogger 1 $*

#Pick one of the following and verify the astdb.txt file exist
#ASL with Supermon Installed
#ASTDB="/var/www/html/supermon/astdb.txt"
#HamVOIP
ASTDB="/var/log/asterisk/astdb.txt"

# Callsign lookup from astdb.txt if the script is not running correctly comment this out
# credit David KB4FXC
CALL=$(awk '-F|' '$1 ~ /^'$2'$/ {print $2}' < $ASTDB)

echo "Callsign: $CALL Node $2 connected to node $1 at $(date +%Y-%m-%d.%H:%M:%S):" | mail -s "My repeater" john.doe@aol.com # enter valid email address
echo "Node $2 connected to node $1 at $(date +%Y-%m-%d.%H:%M:%S):" | mail -s "My repeater" john.doe@aol.com # enter valid email address
echo "Node $2 connected to node $1 at $(date +%Y-%m-%d.%H:%M:%S):" | mail -s "My repeater" 6165551212@messaging.sprintpcs.com  #sprint text message
echo "Node $2 connected to node $1 at $(date +%Y-%m-%d.%H:%M:%S):" | mail -s "My repeater" 6165551212@vtext.com # verizon text message

#if you want to use Telegram
#ref: https://blog.bj13.us/2016/09/06/how-to-send-yourself-a-telegram-message-from-bash.html

#curl -s "https://api.telegram.org/bot$API_KEY/sendMessage?chat_id=$CHAT_ID&text=$CALL ($2) connected to node $1 at $(date +%Y-%m-%d.%H:%M:%S)"

#Make sure to replace the variables:
# $API_KEY = the access token from Step 1 in the website
# $CHAT_ID = the chat id from step 2 in the website
#I couldn't get it to work as variables so i had to put the key and Id in the curl line

exit 0



# settings in /etc/ssmtp/ssmtp.conf without the # of course

#FromLineOverride=YES
#root=YOUR_EMAIL_NAME@gmail.com
#hostname=DOMAIN.COM
#mailhub=smtp.gmail.com:587
#AuthUser=YOUR_EMAIL_NAME@gmail.com
#AuthPass=YOUR_EMAIL_PASSWORD
#useSTARTTLS=YES
